development:
  adapter: postgresql
  encoding: unicode
  database: briefly_development
  pool: 5
  username: George
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: briefly_test
  pool: 5
  username: George
  password:
